### ISSUE TITLE
If port 8080 is not free before start serve microApp, it occurs error

### ISSUE THREAD

**Issue by alex1504** [joeldenning/coexisting-vue-microfrontends#13]
## Error

```
app-errors.js:9 Uncaught navbar: Application 'navbar' died in status LOADING_SOURCE_CODE: Error loading http://localhost:8080/app.js
    at HTMLScriptElement.<anonymous> (https://cdnjs.cloudflare.com/ajax/libs/systemjs/6.1.1/system.min.js:4:5825)
```

## Expected

If port 8080 is dominant before start app1, app2, navbar, these port will be automatically use incremental port(that is ok),  but shoud not occurs error.

**Comment by joeldenning** [comment]
To make the local development flow easy for people new to import maps and systemjs, I hard coded the ports. See [here](https://github.com/joeldenning/coexisting-vue-microfrontends/blob/master/root-html-file/index.html#L12)

For deployed production apps, they would not be hard coded.
