### ISSUE TITLE
Isolated styles

### ISSUE THREAD

**Issue by myeveryheart** [joeldenning/coexisting-vue-microfrontends#19]
Hi, I have same style class name like '.app' in app1 and app2.
But there are not Isolated, any ideas?

**Comment by joeldenning** [comment]
A few options:

- use a tool that generates unique hashes for your css classes during build. See https://vue-loader.vuejs.org/guide/scoped-css.html
- name your css classes with the app name as a prefix
- scope your css classes by putting a css class on the dom element container and then having all css classes only apply to things that are children of that container

In react land I usually prefer the first option, using css modules / styled components / emotion / kremling which all scope their css. For vue, check out scopes css with vue-loader.
