### ISSUE TITLE
how to build and deploy?

### ISSUE THREAD

**Issue by linchanglin** [joeldenning/coexisting-vue-microfrontends#2]
could you tell me how to build this project and how to deploy it in production environment ?
thanks a lot , and waiting for you reply.

**Comment by joeldenning** [comment]
1. Separate each app into its own repo.
2. Use a CI. During the CI on the master branch, do `vue build`.
3. Make sure the file names or directory structure is unique for each build, using the git commit or similar.
4. During the CI, upload the built files to a CDN. For example, use `aws` cli to upload to S3.
5. During the CI, update a deployed import map to point to a new version of the code. Use https://github.com/joeldenning/import-map-overrides for this.

Example for a react project, which does all this: https://github.com/openmrs/openmrs-esm-root-config/blob/master/.travis.yml
