### ISSUE TITLE
The created app by @vue/cli 4.0.3  cannot be microserviced !

### ISSUE THREAD

**Issue by aisujian** [joeldenning/coexisting-vue-microfrontends#20]
![3](https://user-images.githubusercontent.com/33425635/67068618-37d73e00-f1ad-11e9-828d-0212e0e25a38.jpg)
Then
![4](https://user-images.githubusercontent.com/33425635/67068673-5e957480-f1ad-11e9-8869-d63da4885710.jpg)
![5](https://user-images.githubusercontent.com/33425635/67068720-7836bc00-f1ad-11e9-91a3-c4ff5f80b7f9.jpg)
![6](https://user-images.githubusercontent.com/33425635/67068731-7cfb7000-f1ad-11e9-89b1-747b98532f6a.jpg)
![7](https://user-images.githubusercontent.com/33425635/67068735-7ec53380-f1ad-11e9-8176-c483995cb488.jpg)
![8](https://user-images.githubusercontent.com/33425635/67068738-81c02400-f1ad-11e9-8144-a6778cfecb4b.jpg)
![9](https://user-images.githubusercontent.com/33425635/67068744-8389e780-f1ad-11e9-99c1-67f684178ac1.jpg)
Then run root-html-file:
![Jietu20191018-135132](https://user-images.githubusercontent.com/33425635/67069117-9c46cd00-f1ae-11e9-86b2-a22bc2978529.jpg)
![Jietu20191018-135201](https://user-images.githubusercontent.com/33425635/67069118-9cdf6380-f1ae-11e9-86cb-c2a7cad74023.jpg)
There are two solutions:
1:
![Jietu20191018-135242](https://user-images.githubusercontent.com/33425635/67069122-9d77fa00-f1ae-11e9-8b2e-ae07e4b19167.jpg)
Navbar address changed to "http://localhost:8080/js/app.js";
But the resource file address in it will be incorrect;

2:
![Jietu20191018-135502](https://user-images.githubusercontent.com/33425635/67069192-e760e000-f1ae-11e9-890c-b4b3a402ed87.jpg)
Change packaging to UMD format

Please tell me your @vue-cli version or how to configure it. Thank you.

**Comment by aisujian** [comment]
Both methods result in static resource address errors;
![Jietu20191018-140030](https://user-images.githubusercontent.com/33425635/67069436-ae753b00-f1af-11e9-92a6-b1cbb26de409.jpg)

**Comment by aisujian** [comment]
The problem is solved.

This kind of error will not occur in project packaging generated with @ Vue / cli 3.0.

If you use @ Vue / cli4.0 to build a project, you need to add the webpack configuration in vue.config.js.

config.output.filename('app.js').library('appname').libraryTarget('umd').end();

**Comment by joeldenning** [comment]
Are you using vue-cli-plugin-single-spa? It already modifies the webpack config such that the output bundle is umd (see [here](https://github.com/CanopyTax/vue-cli-plugin-single-spa/blob/7ae5927b09fa6403680f3222ddc6e73d4274da8c/index.js#L14)). You should not need to do it yourself.

Note that if there are changes we need to make to the webpack config to support vue cli 4 that we should submit PRs to single-spa-vue and vue-cli-plugin-single-spa.
