### ISSUE TITLE
How can I import components?

### ISSUE THREAD

**Issue by wakeupmh** [joeldenning/coexisting-vue-microfrontends#23]
**How can I import a component?**
 I'm trying to do that but always throw this anoying error: 
``` 
Module not found: Error: Can't resolve '/components/home.vue' in 'D:\estudos\microfrontend\single-spa-app\src\vue'
 @ ./src/vue/main.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/vue/main.vue?vue&type=script&lang=js&) 4:0-40 7:10-14
 @ ./src/vue/main.vue?vue&type=script&lang=js&
 @ ./src/vue/main.vue
 @ ./src/vue/vue.app.js
 @ ./single-spa.config.js
``` 
If you could help me this is my [repo](https://github.com/wakeupmh/microfrontend/tree/master/single-spa-app).

**Comment by joeldenning** [comment]
Change https://github.com/wakeupmh/microfrontend/blob/c64954ba4635c23d8a83b2945485282f5ab53bc9/single-spa-app/src/vue/main.vue#L5 to not have a leading `/` in the import.

`import Home from 'components/home.vue'`

Then modify your webpack config to have the following:

`path.resolve(__dirname, 'src/vue'),`

(add this to the `resolve.modules` part) https://github.com/wakeupmh/microfrontend/blob/c64954ba4635c23d8a83b2945485282f5ab53bc9/single-spa-app/webpack.config.js#L39

**Comment by wakeupmh** [comment]
Thanks so mucho, your projecto is awesome!!!! 🤩🤘
