### ISSUE TITLE
how to deploy to nginx server, please show detail

### ISSUE THREAD

**Issue by page1990** [joeldenning/coexisting-vue-microfrontends#34]

**Comment by joeldenning** [comment]
1. Run `npm install` in each microfrontend
2. Run `npm run build` in each microfrontend
3. Copy the `dist` directory from each microfrontend to the server running Nginx
4. Copy the index.html file for the root config into the nginx server.

See https://github.com/joeldenning/coexisting-vue-microfrontends/blob/master/.travis.yml and https://github.com/CanopyTax/import-map-deployer/tree/master/examples/ci-for-javascript-repo for some example files that show what a CI process can look like for this.
