### ISSUE TITLE
Uncaught Error: systemjs-webpack-interop: There is no such module 'app1' in the SystemJS registry. Did you misspell the name of your module?

### ISSUE THREAD

**Issue by lovemeplz** [joeldenning/coexisting-vue-microfrontends#35]
hello, thanks for your work.  i cloned your repo and started it,. when i started app1, the console told me this, how can i fix this?

![image](https://user-images.githubusercontent.com/22073934/71433804-316cc180-271c-11ea-9db1-6ee35e6408d9.png)

**Comment by joeldenning** [comment]
Do not go directly to http://localhost:8081 in your browser. Instead, follow [the instructions for local development](https://github.com/joeldenning/coexisting-vue-microfrontends#local-development----one-app-at-a-time) instead.
