### ISSUE TITLE
When I don't start the root service, but I start the app1 service

### ISSUE THREAD

**Issue by kavinluo** [joeldenning/coexisting-vue-microfrontends#42]
When I don't start the root service, but I start the app1 service
Address: http://localhost:8081

![image](https://user-images.githubusercontent.com/7992924/75213077-0c500a00-57c4-11ea-9734-2ad50402f962.png)
I did the following!
```js
cd app1
npm i
npm run serve
```
-----

The information I see is as follows, individual APP1 can not work, I understand it should be able to work independently, but it can not! When I start the root service at the same time, URL: http://localhost:5000/app1 It works

**Comment by ssy-tom** [comment]
me，too

**Comment by joeldenning** [comment]
You should not go to each application individually in the browser, but instead follow the instructions in the Readme. In other words, never go to http://localhost:8081 directly to run app1. See the following links for instructions:

- https://github.com/joeldenning/coexisting-vue-microfrontends#local-development----one-app-at-a-time

- https://github.com/joeldenning/coexisting-vue-microfrontends#local-development----all-at-once
