### ISSUE TITLE
When I visited it, I found that it didn't seem to work anymore

### ISSUE THREAD

**Issue by kavinluo** [joeldenning/coexisting-vue-microfrontends#46]
https://coexisting-vue-microfrontends.surge.sh/

![image](https://user-images.githubusercontent.com/7992924/76404920-49222080-63c2-11ea-89dc-99ecc448edbb.png)

**Comment by joeldenning** [comment]
Thanks for the report - it looks like a recent commit must have broken it. I'll take a look at this later.

Note that this example repository is no longer the most up-to-date example - you can check out github.com/vue-microfrontends as a more complete example.

**Comment by joeldenning** [comment]
Fixed in https://github.com/joeldenning/coexisting-vue-microfrontends/commit/b297814e0ecb4eded141db2e226877dcceabb453. This was a regression bug caused by https://github.com/joeldenning/coexisting-vue-microfrontends/commit/9b680845fafbfee1183cd3ab8059e7e991afa04b
