### ISSUE TITLE
vue-cli3

### ISSUE THREAD

**Issue by yangangzhang** [joeldenning/coexisting-vue-microfrontends#5]
Sorry to trouble you again. I have two problem.

1. I use vue-cli3 to make a project, modify according to app1, but error
![image](https://user-images.githubusercontent.com/20433039/64340989-00a43780-d01a-11e9-9610-ac55b4fcf947.png)
2. I have deploy the app1 and app2 in the 3001 server, then  click app1, make a error
![image](https://user-images.githubusercontent.com/20433039/64341342-ba9ba380-d01a-11e9-8067-308cd2fbdb2d.png)
Only if I refresh my browser, the picture will appear.

**Comment by joeldenning** [comment]
> 1. vue is not defined

For this one, verify the following things are correct:
- `vue` should be an external in your vue config. See [example](https://github.com/joeldenning/coexisting-vue-microfrontends/blob/master/app1/vue.config.js#L6)
- `vue` should exist in your import map. See [example](https://github.com/joeldenning/coexisting-vue-microfrontends/blob/master/root-html-file/index.html#L16)
- The url to `vue` should point to the UMD build. For example, [https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.js](https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.js)
- You should be able to run the following in the browser console to verify that it is working:

```js
System.import('vue').then(vue => console.log(vue))
```

> 2. I have deploy the app1 and app2 in the 3001 server, then click app1, make a error.  Only if I refresh my browser, the picture will appear.

That is very unusual. Especially that it works after you refresh the page. Could you provide more details?

**Comment by yangangzhang** [comment]
Sorry , i don't add 'vue-cli-plugin-single-spa' in package.json。

If I use vuex, can I refer to vue as well? Is there anything to pay attention to?

**Comment by joeldenning** [comment]
[Webpack public path]() should be the prefix for your asset urls. See the following links:

- https://single-spa.js.org/docs/faq.html#code-splits
- https://webpack.js.org/guides/public-path/#on-the-fly
