### ISSUE TITLE
codes can not  be cloned

### ISSUE THREAD

**Issue by qinghua5453** [joeldenning/coexisting-vue-microfrontends#51]
codes can not  be cloned

**Comment by joeldenning** [comment]
Hi @qinghua5453 - I verified just now that I was able to clone it. Could you please clarify what problem you are reporting?

<img width="580" alt="image" src="https://user-images.githubusercontent.com/5524384/77087422-b89e9e00-69c8-11ea-9220-481409a5858b.png">
