### ISSUE TITLE
My current needs need to be able to communicate in various projects and pass data to each other for access.

### ISSUE THREAD

**Issue by kavinluo** [joeldenning/coexisting-vue-microfrontends#53]
My current needs need to be able to communicate in various projects and pass data to each other for access. But the current functions should not be realized?

**Comment by joeldenning** [comment]
Hi @kavinluo - there are several methods of communicating between microfrontends, including simple `import` / `export`.

Here is the documentation for how you can accomplish it: https://single-spa.js.org/docs/recommended-setup#inter-app-communication
