### ISSUE TITLE
component: () => import( /* webpackChunkName: "about" */ './views/About.vue')

### ISSUE THREAD

**Issue by yangangzhang** [joeldenning/coexisting-vue-microfrontends#6]
Hello,I built the app3 project with reference to APP2, but in both projects, when I clicked route about, an error occurred.
![error](https://user-images.githubusercontent.com/20433039/64405383-84f5c980-d0b1-11e9-8f84-75bbbac689fe.gif)

Because when you switch app2 or app3, the URL address of about.js does not change, but when you refresh it, it becomes the correct address.

Accessing a large subapp, I found that the problem caused by lazy routing loading prevented the handover from successfully switching to other apps. 
If you don't use routing lazy loading, there's no problem.

**Comment by joeldenning** [comment]
Try running `System.resolve('app3')` to see what the url is for app3. It might return a promise, in which case do `System.resolve('app3').then(url => console.log(url))`. Is that url correct?

**Comment by yangangzhang** [comment]
> Try running `System.resolve('app3')` to see what the url is for app3. It might return a promise, in which case do `System.resolve('app3').then(url => console.log(url))`. Is that url correct?

Yes, the url is right. The result  is follow:
System.resolve('app3').then(url => console.log(url))
VM880:1 http://localhost:9527/app.js
Promise {<resolved>: undefined}

**Comment by yangangzhang** [comment]
I found a solution to this problem.

The app2
``` 
router.js

{
      path: '/app2/about',
      name: 'about',
      // route level code-splitting
      // this generates a separate chunk (about.[hash].js) for this route
      // which is lazy-loaded when the route is visited.

      component: () => import( /* webpackChunkName: "about2" */ './views/About.vue')

    }
```

The app3
``` 
router.js

{
      path: '/app3/about',
      name: 'about',
      // route level code-splitting
      // this generates a separate chunk (about.[hash].js) for this route
      // which is lazy-loaded when the route is visited.

      component: () => import( /* webpackChunkName: "about3" */ './views/About.vue')

    }
```
Different subapps have different `webpackChunkName` names

![image](https://user-images.githubusercontent.com/20433039/64498977-a2ad7380-d2e9-11e9-82f7-2329bc1263d1.png)

**Comment by yangangzhang** [comment]
In short,Accessing a large subapp, I found that other problems caused by lazy routing loading prevented the handover from successfully switching to other apps.
If you don't use routing lazy loading, there's no problem.

**Comment by yangangzhang** [comment]
![error1](https://user-images.githubusercontent.com/20433039/64501038-5450a280-d2f2-11e9-8992-a703d40ad2a8.gif)

**Comment by yangangzhang** [comment]
In short,Accessing a large subapp, I found that other problems caused by lazy routing loading prevented the handover from successfully switching to other apps.
If you don't use routing lazy loading, there's no problem.


 other problems
![error1](https://user-images.githubusercontent.com/20433039/64501053-6599af00-d2f2-11e9-9a73-9c312d463e19.gif)

**Comment by joeldenning** [comment]
Can you create an issue on single-spa-angular, with a link to a github repo that reproduces the problem.

Maybe title it "Lazy loaded routes cause errors"

**Comment by yangangzhang** [comment]
A github repo
https://github.com/yangangzhang/coexisting-vue-microfrontends
You can test the problem above.
Thanks again
