### ISSUE TITLE
vue 3 and vue-router 4

### ISSUE THREAD

**Issue by musashiM82** [joeldenning/coexisting-vue-microfrontends#70]
hi
could you create an example of import map with vue 3 and vue-router 4 please?
thanks

**Comment by joeldenning** [comment]
Hi @musashiM82 - this repository is no longer the encouraged example to look at, as described in the Readme. Instead check out https://github.com/vue-microfrontends. We plan on upgrading that example to Vue 3 in the coming weeks. If you have interest in helping, feel free to submit pull requests.

**Comment by musashiM82** [comment]
hi @joeldenning, I tried to create an example with vue 3 and vue-router 4 but I have some issues.
could you check my code please?
https://github.com/musashiM82/root-config
https://github.com/musashiM82/header
https://github.com/musashiM82/app1
you can reuse it for create an updated example if you want
thanks

**Comment by joeldenning** [comment]
I pulled the repos, here are the fixes:

https://github.com/musashiM82/header/pull/1
https://github.com/musashiM82/root-config/pull/1
https://github.com/musashiM82/app1/pull/1

**Comment by musashiM82** [comment]
thank you 👍

**Comment by musashiM82** [comment]
Hi @joeldenning , sorry if I'm boring you, but I think there is some issue with single-spa now because if you run that projects you can see these following strange behaviours

![issue1](https://user-images.githubusercontent.com/41707194/100608084-35319c80-330c-11eb-8168-2b886c0bb2f4.png)

![issue2](https://user-images.githubusercontent.com/41707194/100608088-36fb6000-330c-11eb-9a86-f079be94d3df.png)

**Comment by joeldenning** [comment]
@musashiM82 feel free to join our [slack workspace](https://join.slack.com/t/single-spa/shared_invite/zt-j4c38g92-JmV7O~35dkN1CnaBkK7NTw) or [create a new github issue](https://github.com/single-spa/single-spa/issues/new/choose). Myself and others can help diagnose the issue in your screenshot.
