### ISSUE TITLE
what if we use third-party ui library like element-ui,and has to import seperate css file

### ISSUE THREAD

**Issue by j-joker** [joeldenning/coexisting-vue-microfrontends#76]
can we just link the css file in the load function and unlink  the file in the unmount hook function?

**Comment by joeldenning** [comment]
You can load CSS files in the loading function, or in the bootstrap lifecycle function. Unmounting the `<link>` from the DOM during unmount cleans up memory and avoids collisions.

**Comment by j-joker** [comment]
Thank you for answering my question
