### ISSUE TITLE
window.getPublicPath is not a function

### ISSUE THREAD

**Issue by wangxueyou110** [joeldenning/coexisting-vue-microfrontends#8]
window.getPublicPath is not a function

**Comment by yangangzhang** [comment]
> window.getPublicPath is not a function

子项目中是否有set-public-path.js，是否正确引入

**Comment by wangxueyou110** [comment]
set-public-path.js:1 Uncaught TypeError: window.getPublicPath is not a function
    at Object../src/set-public-path.js (set-public-path.js:1)
    at __webpack_require__ (bootstrap:723)
    at fn (bootstrap:100)
    at Module../src/main.js (HelloWorld.vue?7a45:1)
    at __webpack_require__ (bootstrap:723)
    at fn (bootstrap:100)
    at Object.0 (Home.vue?3b23:1)
    at __webpack_require__ (bootstrap:723)
    at bootstrap:790
    at bootstrap:790

图片上传不了

**Comment by wangxueyou110** [comment]
直接项目下下来，按他步骤跑不起来

**Comment by yangangzhang** [comment]
> 直接项目下下来，按他步骤跑不起来

1. 截图直接可以拖拽到github上，自动上传
2. 项目下载之后依赖是否安装正确，最好使用cnpm
3. 对，就是先把项目下来，别接入自己的项目

**Comment by wangxueyou110** [comment]
1.截图直接可以拖拽到github上，自动上传好像失效了，我这边传不上

**Comment by wangxueyou110** [comment]
项目我就是用cnpm装的，我没有接自己的项目就是他的项目跑不起来

**Comment by wangxueyou110** [comment]
你项目下载下来可以跑吗

**Comment by wangxueyou110** [comment]
![image](https://user-images.githubusercontent.com/30291910/65210125-c08a8d80-dacc-11e9-8ebf-5132f8996f82.png)
![image](https://user-images.githubusercontent.com/30291910/65210134-c5e7d800-dacc-11e9-9cb0-045c853bbac4.png)
现在图片可以上传了，之前可能网不好

**Comment by wangxueyou110** [comment]
发现问题了，是有个端口被占用了

**Comment by yangangzhang** [comment]
> ![image](https://user-images.githubusercontent.com/30291910/65210125-c08a8d80-dacc-11e9-8ebf-5132f8996f82.png)
> ![image](https://user-images.githubusercontent.com/30291910/65210134-c5e7d800-dacc-11e9-9cb0-045c853bbac4.png)
> 现在图片可以上传了，之前可能网不好

1. 刚才重新下载项目测试了一下，可以跑起来。
2. 建议你删除所有的node_modules然后重新安装，在跑起来
3. 这个项目问题还是不少的，可以研究，最好是使用淘宝qiankun技术方案

**Comment by yangangzhang** [comment]
> 发现问题了，是有个端口被占用了

做微前端的项目，注意端口，因为从开发到部署，端口太多了，而且必须要严格kill

**Comment by joeldenning** [comment]
Note that I have updated this project to use [systemjs-webpack-interop](https://github.com/joeldenning/systemjs-webpack-interop). This removed the `getPublicPath` function.

See https://github.com/joeldenning/coexisting-vue-microfrontends/commit/1253942d350e917a19a37bf8796e5589d7e49c55 for more information.

**Comment by wenwen1995** [comment]
@joeldenning , Hi,can you tell us why to use  systemjs-webpack-interop and removed the `getPublicPath` function ?

**Comment by joeldenning** [comment]
systemjs-webpack-interop has some features that getPublicPath did not, including ability to calculate a public path that is multiple directories above where the entry file is.

Using systemjs@6 is part of the core team's [recommended setup](), which is why it is encouraged in this repo.

Vue CLI uses webpack@>=4.30, so I don't see that as a problem.

You can read more about why we're doing this at all and the reasoning behind it at https://single-spa.js.org/docs/faq/#code-splits
