### ISSUE TITLE
How to add SSR the proper way to this project?

### ISSUE THREAD

**Issue by SystemDZ** [joeldenning/coexisting-vue-microfrontends#83]

**Comment by joeldenning** [comment]
This example is now deprecated, as noted in the readme. SSR was never the intention of this example.

**Comment by SystemDZ** [comment]
I understand, Thanks
Is it possible to add SSR then to this repo?

**Comment by joeldenning** [comment]
Yes, single-spa supports SSR. See https://single-spa.js.org/docs/ssr-overview
