### ISSUE TITLE
请问下这个怎么打包呀

### ISSUE THREAD

**Issue by 869123771** [joeldenning/coexisting-vue-microfrontends#9]
how to package microfrontends project

**Comment by joeldenning** [comment]
Could you help me understand your question better?

Here are a few examples and tools to look at that might work for you:

- https://single-spa.js.org/docs/faq.html#what-does-the-ci-cd-process-look-like
- https://github.com/joeldenning/coexisting-vue-microfrontends/blob/master/.travis.yml
- https://github.com/openmrs/openmrs-esm-home/blob/master/.travis.yml
- https://openmrs-spa.org/frontend/import-map.json

**Comment by suedar** [comment]
@joeldenning He was asking how to pack the project.
@869123771 Actually I think you should have a look at the `.travis.yml` file.

**Comment by joeldenning** [comment]
👍 thanks suedar. Yes, the `.travis.yml` file shows how to build this project.
